<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DI-108" name="dkosh.tc.TCForm" tests="2" failures="1" timestamp="14 Mar 2020 06:41:42 GMT" time="26.119" errors="0">
  <testcase name="TC_dK_006" time="15.174" classname="dkosh.tc.TCForm">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [New(Draft)] but found [In Active],
	expected [Modify Form - CV Application Form] but found [Modify form - CV Application Form]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [New(Draft)] but found [In Active],
expected [Modify Form - CV Application Form] but found [Modify form - CV Application Form]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at dkosh.tc.TCForm.TC_dK_006(TCForm.java:482)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TC_dK_006 -->
  <testcase name="TC_Login" time="10.945" classname="dkosh.tc.TCForm"/>
</testsuite> <!-- dkosh.tc.TCForm -->
